services:
  - type: web
    name: one-piece-spoiler-bot
    runtime: python
    buildCommand: pip install -r requirements.txt && playwright install chromium
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHANNEL_ID
        sync: false
      - key: MONGO_URI
        sync: false
