services:
  - type: web
    name: one-piece-spoiler-bot
    runtime: python
    buildCommand: pip install -r requirements.txt && playwright install chromium --with-deps
    startCommand: python main.py
    envVars:
      - key: TWITTER_BEARER_TOKEN
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHANNEL_ID
        sync: false
      - key: MONGO_URI
        sync: false
